// ====== PLACES DATA ======
const places = [
  { name: "جبل السودة", region: "أبها", regionGroup: "south", tag: "أعلى قمة", desc: "أعلى قمة في المملكة على ارتفاع ٣٠٠٠ متر، مغطاة بالضباب والغابات العرعرية الكثيفة.", season: "صيفاً", temp: "١٢° — ٢٢°", img: "jabal-soudah.jpg", lat: 18.25, lng: 42.37 },
  { name: "أشجار الجاكرندا", region: "الباحة", regionGroup: "south", tag: "ربيعي", desc: "ظاهرة الإزهار البنفسجي الساحرة التي تحوّل المدينة إلى لوحة فنية في الربيع.", season: "مارس — مايو", temp: "١٨° — ٢٥°", img: "jacaranda-baha.jpg", lat: 20.0, lng: 41.47 },
  { name: "غابات رغدان", region: "الباحة", regionGroup: "south", tag: "غابات", desc: "غابة العرعر والزيتون البري التي تمتد على المرتفعات بإطلالات خلابة على السراة.", season: "طوال السنة", temp: "١٥° — ٢٤°", img: "raghadan-forest.jpg", lat: 20.01, lng: 41.46 },
  { name: "جزر فرسان", region: "جازان", regionGroup: "south", tag: "محمية بحرية", desc: "أرخبيل من الجزر الكنزية في البحر الأحمر، موطن للغزال الإدمي وطيور النورس النادرة.", season: "أكتوبر — مارس", temp: "٢٤° — ٣٠°", img: "farasan-islands.jpg", lat: 16.7, lng: 42.12 },
  { name: "وادي لجب", region: "جازان", regionGroup: "south", tag: "وادي", desc: "وادٍ عميق محاط بالمنحدرات الصخرية والمياه الجارية على مدار السنة.", season: "شتاءً وربيعاً", temp: "٢٠° — ٢٨°", img: "wadi-lajab.jpg", lat: 17.62, lng: 43.0 },
  { name: "قرية ذي عين", region: "الباحة", regionGroup: "south", tag: "تراث", desc: "قرية أثرية مبنية على جبل من الرخام الأبيض، محاطة بمزارع الموز والكادي.", season: "طوال السنة", temp: "١٦° — ٢٦°", img: "thee-ain.jpg", lat: 19.93, lng: 41.44 },
  { name: "العُلا", region: "المدينة المنورة", regionGroup: "west", tag: "تراث عالمي", desc: "وادي السحر بمقابره النبطية المنحوتة في الصخر وتشكيلات الحجر الرملي الأسطورية.", season: "أكتوبر — أبريل", temp: "١٨° — ٢٨°", img: "alula.jpg", lat: 26.62, lng: 37.92 },
  { name: "جزر أملج", region: "تبوك", regionGroup: "west", tag: "شواطئ", desc: "مالديف السعودية — مياه فيروزية صافية وشعاب مرجانية فريدة.", season: "أكتوبر — مايو", temp: "٢٢° — ٣٠°", img: "umluj.jpg", lat: 25.05, lng: 37.27 },
  { name: "كورنيش جدة", region: "جدة", regionGroup: "west", tag: "ساحلي", desc: "واجهة بحرية ممتدة على البحر الأحمر مع متاحف مفتوحة وفنون تركيبية.", season: "نوفمبر — مارس", temp: "٢٢° — ٢٨°", img: "jeddah-corniche.jpg", lat: 21.54, lng: 39.12 },
  { name: "حافة العالم", region: "الرياض", regionGroup: "center", tag: "مغامرة", desc: "منحدر صخري درامي في جبال طويق يطلّ على وادٍ يمتد لما لا نهاية.", season: "أكتوبر — أبريل", temp: "١٥° — ٢٥°", img: "edge-of-world.jpg", lat: 24.83, lng: 46.17 },
  { name: "وادي حنيفة", region: "الرياض", regionGroup: "center", tag: "بيئي", desc: "مشروع إعادة تأهيل بيئي حوّل الوادي إلى متنزه طبيعي مع مياه جارية وأشجار النخيل.", season: "طوال السنة", temp: "١٨° — ٣٠°", img: "wadi-hanifah.jpg", lat: 24.63, lng: 46.72 },
  { name: "واحة الأحساء", region: "الأحساء", regionGroup: "east", tag: "اليونسكو", desc: "أكبر واحة نخيل في العالم، مدرجة في قائمة التراث العالمي لليونسكو.", season: "أكتوبر — مارس", temp: "٢٠° — ٢٨°", img: "alahsa-oasis.jpg", lat: 25.38, lng: 49.59 },
  { name: "جبل القارة", region: "الأحساء", regionGroup: "east", tag: "كهوف", desc: "تكوين جبلي فريد بكهوفه الباردة في الصيف والدافئة في الشتاء.", season: "طوال السنة", temp: "١٨° — ٣٢°", img: "jabal-qara.jpg", lat: 25.4, lng: 49.68 },
  { name: "محمية الطبيق", region: "تبوك", regionGroup: "north", tag: "محمية ملكية", desc: "محمية صحراوية شاسعة موطن للنمر العربي والوعل النوبي.", season: "نوفمبر — مارس", temp: "١٠° — ٢٢°", img: "tubaiq-reserve.jpg", lat: 28.18, lng: 37.25 },
  { name: "جبال اللوز", region: "تبوك", regionGroup: "north", tag: "ثلوج", desc: "الجبال الوحيدة في المملكة التي تكسوها الثلوج شتاءً، بإطلالات بانورامية مذهلة.", season: "ديسمبر — فبراير", temp: "-٢° — ١٠°", img: "jabal-lawz.jpg", lat: 28.65, lng: 36.13 },
];
